// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: (() => {
      const url = process.env.DATABASE_URL || process.env.POSTGRES_URL;
      if (!url) {
        throw new Error(
          "Missing required environment variable: DATABASE_URL (or POSTGRES_URL as fallback)."
        );
      }
      return url;
    })(),
  },
});
